Fixed clientStart and serverStart to work with delay

diff --git a/clientStart b/clientStart
--- a/clientStart
+++ b/clientStart
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-# Give 2 port number on command line to run
-if [ "$#" -ne 2 ] && [ "$#" -ne 4 ]; then
-  echo "usage: clientStart <port1> <port2> [<port3> <port4>]"
+# Check for proper number of arguments
+if [ "$#" -lt 2 ] || [ "$#" -gt 5 ]; then
+  echo "usage: clientStart <port1> <port2> [<port3> <port4>] [<delay>]"
   exit 1
 fi
 
@@ -13,11 +13,25 @@ if ! [[ $1 =~ $re ]] || ! [[ $2 =~ $re ]] ; then
   exit 1
 fi
 
-# Check 3rd and 4th argument if exists
-if [ "$#" -eq 4 ]; then
+# Check delay for two players
+if [ "$#" -eq 3 ]; then
+  if ! [[ $3 =~ $re ]]; then
+    echo "Error: invalid delay"
+    exit 1
+  fi
+fi
+
+# Check 3rd and 4th argument if exists as well as delay
+if [ "$#" -ge 4 ]; then
   if ! [[ $3 =~ $re ]] || ! [[ $4 =~ $re ]] ; then
     echo "Error: non-integer value found"
     exit 1
+  fi
+  if [ "$#" -eq 5 ]; then
+    if ! [[ $5 =~ $re ]]; then
+      echo "Error: invalid delay"
+      exit 1
+    fi
   fi
 fi
 
@@ -28,7 +42,7 @@ if [ "$1" -le 1024 ] || [ "$2" -le 1024 ]; then
 fi
 
 # Check 3rd and 4th
-if [ "$#" -eq 4 ]; then
+if [ "$#" -ge 4 ]; then
   if [ "$3" -le 1024 ] || [ "$4" -le 1024 ]; then
     echo "Error: Port numbers must be above 1024"
     exit 1
@@ -36,20 +50,26 @@ if [ "$#" -eq 4 ]; then
 fi
 
 # Cannot use same port numbers
-if [ "$#" -eq 2 ]; then
+if [ "$#" -eq 2 ] || [ "$#" -eq 3 ]; then
   if [ "$1" -eq "$2" ]; then
     echo "Error: same port number detected"
     exit 1
   fi
   echo "Running 2 player"
-  java -cp build/libs/Quoridor-all.jar GameClient localhost:$1 localhost:$2
-  exit 0
+  if [ "$#" -eq 2 ]; then
+    java -cp build/libs/Quoridor-all.jar GameClient localhost:$1 localhost:$2
+    exit 0
+  else
+    java -cp build/libs/Quoridor-all.jar GameClient --delay $3 localhost:$1 localhost:$2
+    exit 0
+  fi
 fi
 
 # Check 4 ports
 ck=0
-if [ "$#" -eq 4 ]; then
-  p1=$1 p2=$2 p3=$3 p4=$4
+size=$#
+if [ "$size" -eq 4 ] || [ "$size" -eq 5 ]; then
+  p1=$1 p2=$2 p3=$3 p4=$4 p5=$5
   #set -- $1 $2 $3 $4
   for a; do
     shift
@@ -64,6 +84,11 @@ if [ "$#" -eq 4 ]; then
     exit 1
   fi
   echo "Running 4 player"
-  java -cp build/libs/Quoridor-all.jar GameClient localhost:$p1 localhost:$p2 localhost:$p3 localhost:$p4
-  exit 0
+  if [ "$size" -eq 4 ]; then
+    java -cp build/libs/Quoridor-all.jar GameClient localhost:$p1 localhost:$p2 localhost:$p3 localhost:$p4
+    exit 0
+  else
+    java -cp build/libs/Quoridor-all.jar GameClient --delay $p5 localhost:$p1 localhost:$p2 localhost:$p3 localhost:$p4
+    exit 0
+  fi
 fi
